
primos:
	gcc -Wall -I./.. primos.c ./../utils.c ./../arrays.c ./../arithmetics.c ./../compare.c ./../variables.c -o primos.out

fibonacci:
	gcc -Wall -I./.. fibonacci.c ./../utils.c ./../arrays.c ./../arithmetics.c ./../compare.c ./../variables.c -o fibonacci.out

factorial:
	gcc -Wall -I./.. factorial.c ./../utils.c ./../arrays.c ./../arithmetics.c ./../compare.c ./../variables.c -o factorial.out

foreachtest:
	gcc -Wall -I./.. foreachtest.c ./../utils.c ./../arrays.c ./../arithmetics.c ./../compare.c ./../variables.c -o foreachtest.out

statistics:
		gcc -Wall -I./.. statistics.c ./../utils.c ./../arrays.c ./../arithmetics.c ./../compare.c ./../variables.c -o statistics.out

clean: 
	rm *.out
	rm *.c

.PHONY: primos fibonacci factorial foreachtest statistics clean